name: Build NextJS Site and Build Node Sass
description: ''
runs: 
  using: composite
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install
      shell: bash
      
    - name: Build 
      run: npm run build
      shell: bash
