name: Deploy Site to Production via SCP
on: 
  workflow_dispatch:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build & Deploy Site
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Build NextJS Site and Demos
        uses: ./.github/actions/build_site
      
      - name: SCP to Production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "public_html/*"
          target: "www/contentblocksjs.com/"
          overwrite: true

      # - name: Deploy via Rsync
      #   uses: burnett01/rsync-deployments@5.1
      #   with:
      #     switches: -avzr --delete
      #     path: out/
      #     remote_path: /home/customer/www/contentblocksjs.com/public_html
      #     remote_host: ${{ secrets.SSH_HOST }}
      #     remote_port: ${{ secrets.SSH_PORT }}
      #     remote_user: ${{ secrets.SSH_USERNAME }}
      #     remote_key: ${{ secrets.SSH_KEY }}
      #     remote_key_pass: ${{ secrets.SSH_KEY_PASSPHRASE }}

      - 
        if: "${{ failure() }}"
        name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3    