name: Test Documentation Site Build & Compile
on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-nextjs-and-nodesass:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v2
      - name: Build Site
        uses: ./.github/actions/build_site